version: 1.0.{build}

init:
- appveyor version
- echo %AVVM_DOWNLOAD_URL%

install:
  - ps: |
      $versions = @("8.7.0", "7.10.1", "6.11.4", "4.8.4", "0.12.18")
      foreach ($version in $versions){
        Install-Product node $version
        $nv = node -v
        $File = $version + ".txt"
        $out = $env:appveyor_build_folder + $File
        $nv | Out-File $File
        if ($nv -eq ("v" + $version)){
          Write-Host "Correct version"
        }
        else{
          exit 1
        }
        Start-Sleep -s 1
      }
      if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
  
artifacts:
  - path: '**\*.txt'

build: off
