version: 1.0.{build}

install:
  - ps: |
      $versions = @("4.6.1", "6.9.0", "0.12.16")
      foreach ($version in $versions){
        Install-Product node $version
        $nv = node -v
        $File = $version + ".txt"
        $out = $env:appveyor_build_folder + $File
        $nv | Out-File $File
        if ($nv -eq ("v" + $version)){
          Write-Host "Correct version"
        }
        else{
          exit 1
        }
      }
      if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
  
artifacts:
  - path: '**\*.txt'

build: off
